apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-server.fullname" . }}
  labels:
    app: {{ .Values.serviceId }}
    {{- include "vllm-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.serviceId }}
