apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  gnb.conf: |-
    {{- if eq .Values.nodeName "skt-6gtb-ars" }}
    {{- .Files.Get "configs/gnb.conf.ars" | nindent 4 }}
    {{- else if eq .Values.nodeName "sys-221he-tnr" }}
    {{- .Files.Get "configs/gnb.conf.sys" | nindent 4 }}
    {{- end }}
  cuphycontroller.yaml: |-
    {{- if eq .Values.nodeName "skt-6gtb-ars" }}
    {{- .Files.Get "configs/cuphycontroller.yaml.ars" | nindent 4 }}
    {{- else if eq .Values.nodeName "sys-221he-tnr" }}
    {{- .Files.Get "configs/cuphycontroller.yaml.sys" | nindent 4 }}
    {{- end }}
  aerial_l1_entrypoint.sh: |-
    {{- .Files.Get "configs/aerial_l1_entrypoint.sh" | nindent 4 }}