apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name  }}-nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 9090;

        location /metrics {
          proxy_pass http://127.0.0.1:8085/metrics;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
